version: "3"
networks:
  internal:

services:
  app:
    build:
      context: ./
      dockerfile: build.Dockerfile
    container_name: app
    networks:
      - internal
    # depends_on:
      # - somecontainer
    # environment:
      # - SOME_ENV=SOME_VALUE
      - APP_DB_HOST=127.0.0.1
      - APP_DB_PORT=5432
      - APP_DB_NAME=database
      - APP_DB_USER=$DB_USER
      - APP_DB_PASSWORD=$DB_PASSWORD
      - APP_HOST=
      - APP_PORT=80
      - APP_PATH=/
    ports:
      - 8080:8080
    # command: somecommand --flag1 --flag2
