version: "3"
networks:
  internal:

services:
  db:
    image: postgres:alpine
    restart: always
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./.tmp/pgdata:/data"
    networks:
      - internal

  app:
    build:
      context: ./
      dockerfile: build.Dockerfile
    container_name: app
    networks:
      - internal
    depends_on:
      - db
    environment:
      APP_DB_HOST: db
      # APP_DB_PORT: 5432
      # APP_DB_NAME: database
      # APP_DB_USER: $DB_USER
      # APP_DB_PASSWORD: $DB_PASSWORD
      # APP_HOST: 
      # APP_PORT: 80
      # APP_PATH: /
    ports:
      - 8080:80
    # command: somecommand --flag1 --flag2
